version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server"]
    networks:
      - net

  db:
    image: "postgres:12.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Kutas123"
    networks:
      - net

  proxies:
    build: .
    volumes:
      - ./proxies:/code
    depends_on:
      - redis
    command: /bin/sh -c "while :; do python -u proxies.py; sleep 1d; done"
    networks:
      - net
    
  scrappers:
    build: .
    volumes:
      - ./scrappers:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    environment:
      - PYTHONUNBUFFERED=0
    command: /bin/sh -c "while :; do python -u main.py; sleep 1d; done"
    networks:
      - net

networks:
  net:
    driver: "bridge"
    
volumes:
  data:
    driver: local